

const AUTH_API_URL=atob('aHR0cHM6Ly9zY3JpcHQuZ29vZ2xlLmNvbS9tYWNyb3Mvcy9BS2Z5Y2J6anV5M0lxREtnWFlKTkVXVnBvQkZPMjN2Yzg3TGVRU0hPXzlVNjVoOXhRUG51SVo5U2lqOHh1YzFVdDlYYjRoVE9JdkEvZXhlYw==');
const S='blog_auth_session',D=3*60*60*1e3;
let E='',F='';
const G=document.getElementById('authOverlay'),H=document.getElementById('blogContent');
const I=document.getElementById('loginScreen'),J=document.getElementById('signupScreen'),K=document.getElementById('forgotScreen'),L=document.getElementById('otpScreen'),M=document.getElementById('resetScreen');
const N=document.getElementById('loginForm'),O=document.getElementById('signupForm'),P=document.getElementById('forgotForm'),Q=document.getElementById('otpForm'),R=document.getElementById('resetForm');
const U=document.getElementById('authError'),V=document.getElementById('authSuccess');

function W(a){[I,J,K,L,M].forEach(b=>{b.style.display='none'}),document.getElementById(a).style.display='block',X()}
function X(){U.style.display='none',V.style.display='none'}
function Y(a){U.textContent=a,U.style.display='block',V.style.display='none'}
function Z(a){V.textContent=a,V.style.display='block',U.style.display='none'}
function $(a,b){const c=document.getElementById(a),d=document.getElementById(a.replace('Button','Text')),e=document.getElementById(a.replace('Button','Loading'));c&&d&&e&&(c.disabled=b,d.style.display=b?'none':'inline',e.style.display=b?'inline-block':'none')}

function _(){const a=localStorage.getItem(S);if(a){try{const b=JSON.parse(a),c=(new Date).getTime();if(b.expires>c)return aa(),!0;localStorage.removeItem(S)}catch(d){localStorage.removeItem(S)}}return!1}
function aa(){G.classList.remove('show'),H.classList.add('authenticated')}
function ab(){G.classList.add('show'),H.classList.remove('authenticated'),W('loginScreen'),setTimeout(()=>{const a=document.getElementById('loginEmail');a&&a.focus()},100)}
function ac(){localStorage.removeItem(S),window.sessionTimerInterval&&clearInterval(window.sessionTimerInterval),ab(),console.log('👋 User logged out successfully')}

async function ad(a,b){console.log('🔄 Making auth request:',a,'to URL:',AUTH_API_URL);try{return await ae(a,b)}catch(c){console.warn('⚠️ Fetch failed, trying JSONP fallback:',c.message);try{return await af(a,b)}catch(d){console.error('❌ Both methods failed');throw new Error('Unable to connect to authentication server. Please try refreshing the page or contact support.')}}}
async function ae(a,b){const c={action:a,...b};console.log('📤 Fetch request data:',c);const d=await fetch(AUTH_API_URL,{method:'POST',headers:{'Content-Type':'text/plain'},body:JSON.stringify(c),mode:'cors',cache:'no-cache'});console.log('📥 Response status:',d.status);if(!d.ok){const e=await d.text();console.error('Server error response:',e);throw new Error(`Server error (${d.status}): ${d.statusText}`)}const f=await d.json();console.log('✅ Fetch result:',f);return f}
function af(a,b){return new Promise((c,d)=>{const e='authCallback_'+Date.now()+'_'+Math.random().toString(36).substr(2,9),f=setTimeout(()=>{g(),d(new Error('Request timeout'))},1e4);function g(){window[e]&&delete window[e],clearTimeout(f);const a=document.getElementById(e);a&&a.remove()}window[e]=function(a){g(),console.log('✅ JSONP result:',a),c(a)};const h=document.createElement('script');h.id=e;const i=new URLSearchParams({callback:e,action:a,...b});h.src=`${AUTH_API_URL}?${i.toString()}`,h.onerror=()=>{g(),d(new Error('Script loading failed'))},document.head.appendChild(h),console.log('📤 JSONP request:',h.src)}})}

N.addEventListener('submit',async function(a){a.preventDefault(),X(),$('loginButton',!0);const b=document.getElementById('loginEmail').value.trim(),c=document.getElementById('loginPassword').value.trim();if(!b||!c)return Y('Please enter both email and password'),$('loginButton',!1),void 0;try{const d=await ad('login',{username:b,password:c});if(d.success){const e={user:d.user,expires:(new Date).getTime()+D};localStorage.setItem(S,JSON.stringify(e)),aa(),document.getElementById('loginEmail').value='',document.getElementById('loginPassword').value=''}else Y(d.message||'Login failed')}catch(e){Y(e.message)}$('loginButton',!1)});
O.addEventListener('submit',async function(a){a.preventDefault(),X(),$('signupButton',!0);const b=document.getElementById('signupEmail').value.trim(),c=document.getElementById('signupPassword').value.trim(),d=document.getElementById('confirmPassword').value.trim();if(!b||!c||!d)return Y('Please fill in all fields'),$('signupButton',!1),void 0;if(c!==d)return Y('Passwords do not match'),$('signupButton',!1),void 0;try{const e=await ad('signup',{username:b,password:c});e.success?(Z(e.message),setTimeout(()=>W('loginScreen'),2e3),document.getElementById('signupEmail').value='',document.getElementById('signupPassword').value='',document.getElementById('confirmPassword').value=''):Y(e.message||'Signup failed')}catch(f){Y(f.message)}$('signupButton',!1)});
P.addEventListener('submit',async function(a){a.preventDefault(),X(),$('forgotButton',!0);const b=document.getElementById('forgotEmail').value.trim();if(!b)return Y('Please enter your email address'),$('forgotButton',!1),void 0;try{const c=await ad('forgot_password',{email:b});c.success?(E=b,Z(c.message),setTimeout(()=>W('otpScreen'),2e3)):Y(c.message||'Failed to send reset code')}catch(d){Y(d.message)}$('forgotButton',!1)});
Q.addEventListener('submit',async function(a){a.preventDefault(),X(),$('otpButton',!0);const b=document.getElementById('otpCode').value.trim();if(!b)return Y('Please enter the 6-digit code'),$('otpButton',!1),void 0;try{const c=await ad('verify_otp',{email:E,otp:b});c.success?(F=b,Z(c.message),setTimeout(()=>W('resetScreen'),2e3)):Y(c.message||'Invalid code')}catch(d){Y(d.message)}$('otpButton',!1)});
R.addEventListener('submit',async function(a){a.preventDefault(),X(),$('resetButton',!0);const b=document.getElementById('newPassword').value.trim(),c=document.getElementById('confirmNewPassword').value.trim();if(!b||!c)return Y('Please fill in both password fields'),$('resetButton',!1),void 0;if(b!==c)return Y('Passwords do not match'),$('resetButton',!1),void 0;try{const d=await ad('reset_password',{email:E,otp:F,newPassword:b});d.success?(Z(d.message),setTimeout(()=>W('loginScreen'),3e3),document.getElementById('newPassword').value='',document.getElementById('confirmNewPassword').value='',E='',F=''):Y(d.message||'Password reset failed')}catch(f){Y(f.message)}$('resetButton',!1)});

document.getElementById('showSignup').addEventListener('click',e=>{e.preventDefault(),W('signupScreen')});
document.getElementById('showLogin').addEventListener('click',e=>{e.preventDefault(),W('loginScreen')});
document.getElementById('showForgotPassword').addEventListener('click',e=>{e.preventDefault(),W('forgotScreen')});
document.getElementById('backToLogin').addEventListener('click',e=>{e.preventDefault(),W('loginScreen')});
document.getElementById('backToForgot').addEventListener('click',e=>{e.preventDefault(),W('forgotScreen')});
document.getElementById('resendOTP').addEventListener('click',async e=>{e.preventDefault();if(E){try{const b=await ad('forgot_password',{email:E});b.success?Z('New code sent to your email'):Y(b.message||'Failed to resend code')}catch(c){Y(c.message)}}});

async function ag(){try{console.log('🔍 Testing server connection...');try{const a=await fetch(AUTH_API_URL,{method:'GET',mode:'cors',cache:'no-cache'});if(a.ok){const b=await a.json();console.log('✅ Server connection successful (fetch):',b);return!0}}catch(c){console.warn('⚠️ Fetch test failed, trying JSONP:',c.message)}return await new Promise(a=>{const b='testCallback_'+Date.now();const c=setTimeout(()=>{h(),a(!1)},5e3);function h(){window[b]&&delete window[b];const a=document.getElementById(b);a&&a.remove();clearTimeout(c)}window[b]=function(d){h(),console.log('✅ Server connection successful (JSONP):',d),a(!0)};const e=document.createElement('script');e.id=b,e.src=`${AUTH_API_URL}?callback=${b}`,e.onerror=()=>{h(),a(!1)},document.head.appendChild(e)})}catch(d){console.error('❌ All connection tests failed:',d);return!1}}
function ah(){window.addEventListener('storage',function(a){if(a.key===S){if(a.newValue===null)ac();else try{const b=JSON.parse(a.newValue),c=(new Date).getTime();b.expires>c&&!H.classList.contains('authenticated')&&aa()||(b.expires<=c&&ac())}catch(d){console.error('Session sync error:',d),ac()}}})}
function ai(){const a=localStorage.getItem(S);if(a)try{const b=JSON.parse(a),c=(new Date).getTime();if(b.expires>c){const d=document.getElementById('authOverlay'),e=document.getElementById('blogContent');d&&d.classList.remove('show'),e&&e.classList.add('authenticated');return!0}else localStorage.removeItem(S)}catch(f){localStorage.removeItem(S)}return!1}
ai();
document.addEventListener('DOMContentLoaded',async()=>{console.log('🚀 Authentication system initializing...'),console.log('📡 Server URL:',AUTH_API_URL),console.log('🔄 Cross-page session sync enabled'),ah();const a=await ag();a||Y('Unable to connect to authentication server. Please check your internet connection and try again.');const b=_();b?(console.log('✅ User authenticated from stored session'),G.classList.remove('show'),H.classList.add('authenticated')):setTimeout(()=>{_()||ab()},100),setInterval(()=>{!_()&&!G.classList.contains('show')&&(console.log('⚠️ Session expired, showing login'),ab())},6e4),setInterval(()=>{const a=localStorage.getItem(S);if(a)try{const b=JSON.parse(a),c=(new Date).getTime(),d=b.expires-c;c<=0&&(console.log('⏳ Session expired, forcing logout'),ac())}catch(e){console.error('Session validation error:',e),ac()}},1e4)});
document.addEventListener('visibilitychange',()=>{!document.hidden&&!_()&&ab()});
H.addEventListener('contextmenu',a=>{H.classList.contains('authenticated')||a.preventDefault()});
document.addEventListener('keydown',a=>{if(!H.classList.contains('authenticated')){a.ctrlKey&&['c','a','s','p'].includes(a.key)&&a.preventDefault();(a.key==='F12'||(a.ctrlKey&&a.shiftKey&&['I','C','J'].includes(a.key))||(a.ctrlKey&&a.key==='U'))&&(a.preventDefault(),Y('Access denied. Please login first.'))}});

